export const SET_LOADING = "SET_LOADING"

export const GET_COURSES = "GET_COURSES"
export const GET_COURSES_SUCCESS = "GET_COURSES_SUCCESS"

export const GET_COURSES_INDEX = "GET_COURSES_INDEX"
export const GET_COURSES_INDEX_SUCCESS = "GET_COURSES_INDEX_SUCCESS"